language: php

php:
  - 7.0
  - 7.1

dist: trusty
sudo: required

before_install:
  -  chmod +x ./scripts/* #thanks https://medium.com/@psaunders
  - ./script/travis_mysql_5.7.sh
  - ./script/mysql-reset-root-password.sh

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

before_script:
  - composer install --dev --prefer-source --no-interaction
  - php artisan migrate:refresh --seed --force