language: php
php:
- 7.0
- 7.1
dist: trusty
sudo: required
before_install:
- chmod +x ./script/*
- ./script/travis_mysql_5.7.sh
- ./script/mysql-reset-root-password.sh
services:
- mysql
before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
- composer install --dev --prefer-source --no-interaction
notifications:
  email: false
